name: 'Test multi-platform Docker images'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    permissions:
      contents: read
      packages: write
    container:
      image: mcr.microsoft.com/azure-cli:latest
      options:
        -v /dev:/dev

    steps:
      - name: 'Docker image test (amd64)'
        shell: bash
        run: |
          echo -ne "AZ_CLI_VERSION="
          az --version | head -n 1 | sed -E 's/.* ([^ ]+)$/\1/'
