name: 'Test standalone'
run-name: '${{ github.ref_type }}_${{ github.ref_name }}@${{ github.triggering_actor }}'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  test-on-linux-x86:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Install required packages (amd64)'
        run: |
          sudo apt-get update && \
          sudo apt-get -y --no-install-recommends install python3-full && \
          sudo apt-get clean && sudo rm -rf "/var/lib/apt/lists/*"
      - name: 'Perform standalone install (amd64)'
        run: |
          ./standalone-install.sh
      - name: 'Azure cloud tools test (amd64)'
        shell: bash
        run: |
          source ./venv/bin/activate
          echo -ne "AZ_CLI_VERSION="
          az --version | head -n 1 | awk '{print $NF}'

  test-on-linux-arm:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Install required packages (arm64)'
        run: |
          sudo apt-get update && \
          sudo apt-get -y --no-install-recommends install python3-full && \
          sudo apt-get clean && sudo rm -rf "/var/lib/apt/lists/*"
      - name: 'Perform standalone install (arm64)'
        run: |
          ./standalone-install.sh
      - name: 'Azure cloud tools test (arm64)'
        shell: bash
        run: |
          source ./venv/bin/activate
          echo -ne "AZ_CLI_VERSION="
          az --version | head -n 1 | awk '{print $NF}'
